maven-develop-build:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export img_tag="latest";
    - docker build --no-cache --pull --build-arg img_tag=$img_tag -t "$CI_REGISTRY_IMAGE:$img_tag" .;
    - export maven_container=$(docker create -w /root/z3-plugin $CI_REGISTRY_IMAGE:$img_tag)
    - docker cp $(pwd)/. $maven_container:/root/z3-plugin
    - docker start -ai $maven_container
    - docker cp $maven_container:/root/z3-plugin/. $(pwd)/.
    - docker rm $maven_container
    - docker rmi $CI_REGISTRY_IMAGE:$img_tag
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - pi
    - shell
    - gitlab-runner-dind
